version: "3.7"

services:
  python:       
    build: 
      dockerfile: ./docker/Dockerfile
      context: ./
    image: testimage
    
    ports:
      - "8888:8888"

    command: 
      jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='local_dev'

    volumes:
      - ./data:/data
      - ./code_:/code_
      - ./notebooks:/notebooks
      - ./reports:/reports
      - ./documents:/documents

